apiVersion: apps/v1
kind: Deployment
metadata:
  name: openresty-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: openresty
  template:
    metadata:
      labels:
        app: openresty
    spec:
      containers:
      - name: openresty
        image: dockermerve/hmac-v4
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /usr/local/openresty/nginx/conf/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: config-volume
        configMap:
          name: openresty-config
